/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TableResizerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEBUG_LOGGING = false;
var DEFAULT_SETTINGS = {
  enableResizer: true,
  minColumnWidth: 50,
  maxColumnWidth: 800,
  saveWidths: true
};
var TableResizerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = Object.assign({}, DEFAULT_SETTINGS);
    this.isDragging = false;
    this.currentTable = null;
    this.currentColumn = -1;
    this.startX = 0;
    this.startWidth = 0;
    this.resizerLine = null;
    this.tableWidths = /* @__PURE__ */ new Map();
    this.mutationObservers = /* @__PURE__ */ new Map();
    this.mutationReapplyPending = false;
    this.isApplyingWidths = false;
    this.widthSaveTimer = null;
    this.keyupDebounceTimer = null;
    this.periodicScanInterval = null;
    this.handleMouseMove = (e) => {
      if (!this.isDragging || !this.currentTable)
        return;
      const diff = e.clientX - this.startX;
      const newWidth = this.startWidth + diff;
      const clampedWidth = Math.max(
        this.settings.minColumnWidth,
        Math.min(this.settings.maxColumnWidth, newWidth)
      );
      this.applyColumnWidth(this.currentTable, this.currentColumn, clampedWidth);
    };
    this.handleMouseUp = () => {
      if (!this.isDragging)
        return;
      const draggedTable = this.currentTable;
      const draggedColumn = this.currentColumn;
      this.isDragging = false;
      document.body.classList.remove("table-resizer-dragging");
      if (draggedTable) {
        const handles = draggedTable.querySelectorAll(".table-resizer-handle");
        handles.forEach((handle) => handle.classList.remove("dragging"));
      }
      if (this.settings.saveWidths && draggedTable) {
        this.updateMarkdownTable(draggedTable);
      }
      this.log(`handleMouseUp: drag ended, column=${draggedColumn}`);
      if (draggedTable && draggedColumn >= 0) {
        const tableId = this.getTableIdentifier(draggedTable);
        const storedWidths = this.tableWidths.get(tableId);
        const expectedWidth = storedWidths == null ? void 0 : storedWidths.get(draggedColumn);
        if (expectedWidth) {
          requestAnimationFrame(() => {
            this.confirmColumnWidth(draggedTable, draggedColumn, expectedWidth, 1);
            requestAnimationFrame(() => {
              this.confirmColumnWidth(draggedTable, draggedColumn, expectedWidth, 2);
              setTimeout(() => {
                this.confirmColumnWidth(draggedTable, draggedColumn, expectedWidth, 3);
                this.dumpTableState("after drag (3 confirmations)");
              }, 100);
            });
          });
        }
      }
      this.currentTable = null;
      this.currentColumn = -1;
    };
  }
  log(message, data) {
    if (!DEBUG_LOGGING)
      return;
    const ts = (/* @__PURE__ */ new Date()).toISOString().substring(11, 23);
    const prefix = `[TableResizer ${ts}]`;
    if (data !== void 0) {
      console.log(`${prefix} ${message}`, data);
    } else {
      console.log(`${prefix} ${message}`);
    }
  }
  async onload() {
    this.log("Plugin loading...");
    try {
      this.settings = Object.assign({}, DEFAULT_SETTINGS);
      await this.loadSettings();
      this.log("Settings loaded", this.settings);
      this.registerStyleSheet();
      this.log("Styles registered");
      this.registerEvent(
        this.app.workspace.on("layout-change", () => {
          this.log("Event: layout-change");
          this.dumpTableState("layout-change (before init)");
          this.initTables();
          setTimeout(() => {
            this.applyAllStoredWidths();
            this.dumpTableState("layout-change (after apply)");
          }, 100);
        })
      );
      this.registerEvent(
        this.app.workspace.on("active-leaf-change", () => {
          this.log("Event: active-leaf-change");
          this.dumpTableState("active-leaf-change (before init)");
          this.initTables();
          setTimeout(() => {
            this.applyAllStoredWidths();
            this.dumpTableState("active-leaf-change (after apply)");
          }, 100);
        })
      );
      this.registerEvent(
        this.app.workspace.on("file-open", () => {
          this.log("Event: file-open");
          this.dumpTableState("file-open (before init)");
          setTimeout(() => {
            this.initTables();
            this.applyAllStoredWidths();
            this.dumpTableState("file-open (after apply)");
          }, 200);
        })
      );
      this.registerDomEvent(document, "keyup", () => {
        if (this.keyupDebounceTimer !== null) {
          clearTimeout(this.keyupDebounceTimer);
        }
        this.keyupDebounceTimer = window.setTimeout(() => {
          this.keyupDebounceTimer = null;
          this.log("keyup scan: checking for new tables");
          this.initTables();
          requestAnimationFrame(() => {
            this.applyAllStoredWidths();
          });
        }, 500);
      });
      this.periodicScanInterval = window.setInterval(() => {
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (activeView && this.settings.enableResizer) {
          this.initTables();
          this.applyAllStoredWidths();
        }
      }, 8e3);
      this.registerInterval(this.periodicScanInterval);
      this.log("keyup listener + periodic scan registered");
      this.addCommand({
        id: "toggle-table-resizer",
        name: "Toggle table resizer",
        callback: () => {
          this.settings.enableResizer = !this.settings.enableResizer;
          this.saveSettings();
          new import_obsidian.Notice(`Table resizer ${this.settings.enableResizer ? "enabled" : "disabled"}`);
          this.initTables();
        }
      });
      if (this.app.workspace.onReady) {
        this.app.workspace.onReady(() => {
          setTimeout(() => {
            try {
              this.log("onReady: initializing tables");
              this.dumpTableState("onReady (before init)");
              this.initTables();
              this.applyAllStoredWidths();
              this.dumpTableState("onReady (after init)");
              this.log("Tables initialized (onReady)");
            } catch (err) {
              if (DEBUG_LOGGING)
                console.warn("Error initializing tables:", err);
            }
          }, 100);
        });
      } else {
        setTimeout(() => {
          try {
            this.log("fallback: initializing tables");
            this.dumpTableState("fallback (before init)");
            this.initTables();
            this.applyAllStoredWidths();
            this.dumpTableState("fallback (after init)");
            this.log("Tables initialized (fallback)");
          } catch (err) {
            if (DEBUG_LOGGING)
              console.warn("Error initializing tables:", err);
          }
        }, 500);
      }
      this.log("Plugin loaded successfully");
    } catch (error) {
      console.error("Failed to load Table Resizer plugin:", error);
    }
  }
  registerStyleSheet() {
    try {
      if (document.getElementById("table-resizer-styles")) {
        return;
      }
      const style = document.createElement("style");
      style.id = "table-resizer-styles";
      style.textContent = `
				.table-resizer-handle {
					position: absolute;
					top: 0;
					right: -2px;
					width: 5px;
					height: 100%;
					cursor: col-resize;
					user-select: none;
					z-index: 100;
					opacity: 0;
					transition: opacity 0.2s;
				}

				.table-resizer-handle:hover,
				.table-resizer-handle.dragging {
					background-color: var(--interactive-accent, #7f6df2);
					opacity: 0.5;
				}

				.table-resizer-active td,
				.table-resizer-active th {
					position: relative;
					height: auto;
				}

				/* Prevent empty cells from collapsing \u2014 min-height is unreliable on table-cell */
				.table-resizer-active td:empty::after,
				.table-resizer-active th:empty::after {
					content: '\\00a0';
					display: inline-block;
					line-height: 1.8;
				}

				.table-resizer-active tr {
					height: auto;
				}
			`;
      if (document.head) {
        document.head.appendChild(style);
      } else {
        document.documentElement.appendChild(style);
      }
    } catch (error) {
      if (DEBUG_LOGGING)
        console.error("Error registering stylesheet:", error);
    }
  }
  initTables() {
    try {
      const markdownViews = this.app.workspace.getLeavesOfType("markdown");
      if (!markdownViews || markdownViews.length === 0) {
        this.log("initTables: no markdown views found");
        return;
      }
      this.log(`initTables: processing ${markdownViews.length} markdown view(s)`);
      markdownViews.forEach((leaf) => {
        try {
          const view = leaf.view;
          if (!view || !view.contentEl) {
            return;
          }
          this.setupMutationObserver(view.contentEl);
          const previewEl = view.contentEl.querySelector(".markdown-preview-view") || view.contentEl.querySelector(".markdown-reading-view") || view.contentEl.querySelector(".markdown-preview-sizer");
          if (previewEl) {
            this.log("Found preview element, processing tables...");
            this.processTables(previewEl);
          }
          const sourceEl = view.contentEl.querySelector(".markdown-source-view") || view.contentEl.querySelector(".cm-content") || view.contentEl.querySelector(".CodeMirror-code");
          if (sourceEl) {
            this.log("Found source/edit element, processing tables...");
            this.processTables(sourceEl);
          }
          if (!previewEl && !sourceEl) {
            this.log("No specific view element found, searching in contentEl...");
            this.processTables(view.contentEl);
          }
        } catch (error) {
          if (DEBUG_LOGGING)
            console.warn("Error processing view:", error);
        }
      });
    } catch (error) {
      if (DEBUG_LOGGING)
        console.error("Error in initTables:", error);
    }
  }
  setupMutationObserver(container) {
    if (this.mutationObservers.has(container)) {
      return;
    }
    this.log("MutationObserver: setting up on", container.className || container.tagName);
    let mutationCount = 0;
    const observer = new MutationObserver((mutations) => {
      var _a;
      mutationCount++;
      if (this.isApplyingWidths) {
        return;
      }
      let tableRelated = false;
      let triggerReason = "";
      for (const mutation of mutations) {
        if (mutation.type === "childList") {
          for (const node of mutation.addedNodes) {
            if (node instanceof HTMLElement) {
              if (node.tagName === "TABLE") {
                tableRelated = true;
                triggerReason = `TABLE added (${((_a = node.rows) == null ? void 0 : _a.length) || 0} rows)`;
                break;
              }
              if (node.querySelector("table")) {
                tableRelated = true;
                triggerReason = "node containing TABLE added";
                break;
              }
            }
          }
          if (!tableRelated) {
            for (const node of mutation.removedNodes) {
              if (node instanceof HTMLElement) {
                if (node.tagName === "TABLE" || node.querySelector("table")) {
                  tableRelated = true;
                  triggerReason = "TABLE removed";
                  break;
                }
              }
            }
          }
          if (!tableRelated && mutation.target instanceof HTMLElement) {
            const closestTable = mutation.target.closest("table");
            if (closestTable) {
              tableRelated = true;
              const targetDesc = mutation.target.tagName || mutation.target.nodeName;
              triggerReason = `DOM change inside table (target: ${targetDesc}, added: ${mutation.addedNodes.length}, removed: ${mutation.removedNodes.length})`;
            }
          }
        } else if (mutation.type === "characterData") {
          if (mutation.target instanceof Node && mutation.target.parentElement) {
            const closestTable = mutation.target.parentElement.closest("table");
            if (closestTable) {
              tableRelated = true;
              triggerReason = `characterData change inside table`;
            }
          }
        }
        if (tableRelated)
          break;
      }
      if (tableRelated) {
        this.log(`MutationObserver [#${mutationCount}]: ${triggerReason}`);
        this.scheduleMutationReapply();
      }
    });
    observer.observe(container, {
      childList: true,
      subtree: true,
      characterData: true
    });
    this.mutationObservers.set(container, observer);
    this.log("MutationObserver: registered successfully");
  }
  scheduleMutationReapply() {
    if (this.mutationReapplyPending)
      return;
    this.mutationReapplyPending = true;
    queueMicrotask(() => {
      this.mutationReapplyPending = false;
      this.log("MutationObserver: re-initializing tables");
      this.dumpTableState("before mutation reapply");
      this.initTables();
      requestAnimationFrame(() => {
        this.applyAllStoredWidths();
        requestAnimationFrame(() => {
          this.applyAllStoredWidths();
          this.dumpTableState("after mutation reapply (2x rAF)");
        });
      });
    });
  }
  processTables(container) {
    const tables = container.querySelectorAll("table");
    this.log(`processTables: found ${tables.length} table(s) in container`);
    tables.forEach((table, idx) => {
      if (this.settings.enableResizer) {
        this.enableResizing(table);
        this.applyStoredWidths(table);
      } else {
        this.disableResizing(table);
      }
    });
  }
  enableResizing(table) {
    const hadClass = table.classList.contains("table-resizer-active");
    table.classList.add("table-resizer-active");
    const rows = table.querySelectorAll("tr");
    if (!rows || rows.length === 0) {
      this.log("enableResizing: table has no rows, skipping");
      return;
    }
    const firstRow = rows[0];
    const columnCount = firstRow.querySelectorAll("th, td").length;
    const totalCells = Array.from(rows).reduce((sum, row) => sum + row.querySelectorAll("th, td").length, 0);
    const existingHandles = table.querySelectorAll(".table-resizer-handle").length;
    if (hadClass && existingHandles >= totalCells) {
      this.log(`enableResizing: already active with ${existingHandles} handles, skipping`);
      return;
    }
    if (hadClass && existingHandles < totalCells) {
      this.log(`enableResizing: handles missing (${existingHandles}/${totalCells}), re-adding`);
    } else {
      this.log(`enableResizing: table ${rows.length}x${columnCount}, adding handles`);
    }
    this.isApplyingWidths = true;
    rows.forEach((row) => {
      const cells = row.querySelectorAll("th, td");
      cells.forEach((cell, index) => {
        var _a;
        const el = cell;
        if (!cell.querySelector(".table-resizer-handle")) {
          this.addResizerHandle(el, table, index);
        }
        if (((_a = el.textContent) == null ? void 0 : _a.trim()) === "") {
          el.style.minHeight = "1.8em";
        }
      });
    });
    this.isApplyingWidths = false;
    document.removeEventListener("mousemove", this.handleMouseMove);
    document.removeEventListener("mouseup", this.handleMouseUp);
    document.addEventListener("mousemove", this.handleMouseMove);
    document.addEventListener("mouseup", this.handleMouseUp);
  }
  disableResizing(table) {
    table.classList.remove("table-resizer-active");
    table.style.tableLayout = "";
    const handles = table.querySelectorAll(".table-resizer-handle");
    handles.forEach((handle) => handle.remove());
  }
  addResizerHandle(cell, table, columnIndex) {
    if (cell.querySelector(".table-resizer-handle")) {
      return;
    }
    const handle = document.createElement("div");
    handle.className = "table-resizer-handle";
    handle.dataset.column = columnIndex.toString();
    handle.addEventListener("mousedown", (e) => {
      e.preventDefault();
      e.stopPropagation();
      this.startDrag(e, table, columnIndex);
    });
    handle.addEventListener("touchstart", (e) => {
      e.preventDefault();
      e.stopPropagation();
      const touch = e.touches[0];
      this.startDrag({ clientX: touch.clientX, clientY: touch.clientY }, table, columnIndex);
    }, { passive: false });
    cell.appendChild(handle);
  }
  startDrag(e, table, columnIndex) {
    this.isDragging = true;
    this.currentTable = table;
    this.currentColumn = columnIndex;
    this.startX = e.clientX;
    const firstRow = table.querySelector("tr");
    if (!firstRow)
      return;
    const cell = firstRow.querySelectorAll("th, td")[columnIndex];
    this.startWidth = cell.offsetWidth;
    this.log(`startDrag: column=${columnIndex}, startWidth=${this.startWidth}px, clientX=${e.clientX}`);
    document.body.classList.add("table-resizer-dragging");
    const allHandles = table.querySelectorAll(".table-resizer-handle");
    allHandles.forEach((handle) => {
      if (handle.getAttribute("data-column") === columnIndex.toString()) {
        handle.classList.add("dragging");
      }
    });
  }
  confirmColumnWidth(table, columnIndex, expectedWidth, round) {
    const firstRow = table.querySelector("tr");
    if (!firstRow)
      return;
    const cell = firstRow.querySelectorAll("th, td")[columnIndex];
    if (!cell)
      return;
    const currentWidth = cell.style.width;
    if (currentWidth !== `${expectedWidth}px`) {
      this.log(`confirmColumnWidth round#${round}: width mismatch (expected=${expectedWidth}px, actual=${currentWidth}), re-applying`);
      this.isApplyingWidths = true;
      const rows = table.querySelectorAll("tr");
      rows.forEach((row) => {
        const cells = row.querySelectorAll("th, td");
        if (cells[columnIndex]) {
          const c = cells[columnIndex];
          c.style.width = `${expectedWidth}px`;
          c.style.minWidth = `${expectedWidth}px`;
          c.style.maxWidth = `${expectedWidth}px`;
        }
      });
      this.isApplyingWidths = false;
    }
  }
  applyColumnWidth(table, columnIndex, width) {
    const rows = table.querySelectorAll("tr");
    const tableId = this.getTableIdentifier(table);
    this.log(`applyColumnWidth: table=${tableId}, col=${columnIndex}, width=${width}px, rows=${rows.length}`);
    table.style.tableLayout = "fixed";
    this.isApplyingWidths = true;
    rows.forEach((row) => {
      const cells = row.querySelectorAll("th, td");
      if (cells[columnIndex]) {
        const cell = cells[columnIndex];
        cell.style.width = `${width}px`;
        cell.style.minWidth = `${width}px`;
        cell.style.maxWidth = `${width}px`;
      }
    });
    this.isApplyingWidths = false;
    this.saveTableColumnWidth(table, columnIndex, width);
    requestAnimationFrame(() => {
      const rowsNow = table.querySelectorAll("tr");
      rowsNow.forEach((row) => {
        const cells = row.querySelectorAll("th, td");
        if (cells[columnIndex]) {
          const cell = cells[columnIndex];
          if (cell.style.width !== `${width}px`) {
            this.log(`applyColumnWidth: width was overwritten for col=${columnIndex}, re-applying (rAF)`);
            this.isApplyingWidths = true;
            cell.style.width = `${width}px`;
            cell.style.minWidth = `${width}px`;
            cell.style.maxWidth = `${width}px`;
            this.isApplyingWidths = false;
          }
        }
      });
    });
  }
  saveTableColumnWidth(table, columnIndex, width) {
    const tableId = this.getTableIdentifier(table);
    if (!this.tableWidths.has(tableId)) {
      this.tableWidths.set(tableId, /* @__PURE__ */ new Map());
    }
    this.tableWidths.get(tableId).set(columnIndex, width);
    this.log(`saveTableColumnWidth: table=${tableId}, col=${columnIndex}, width=${width}px, total stored: ${this.tableWidths.size} tables`);
    this.persistWidths();
  }
  serializeWidths() {
    const result = {};
    this.tableWidths.forEach((cols, tableId) => {
      const colObj = {};
      cols.forEach((width, colIndex) => {
        colObj[String(colIndex)] = width;
      });
      if (Object.keys(colObj).length > 0) {
        result[tableId] = colObj;
      }
    });
    return result;
  }
  deserializeWidths(data) {
    this.tableWidths.clear();
    for (const [tableId, cols] of Object.entries(data)) {
      const colMap = /* @__PURE__ */ new Map();
      for (const [colStr, width] of Object.entries(cols)) {
        colMap.set(Number(colStr), width);
      }
      this.tableWidths.set(tableId, colMap);
    }
    this.log(`deserializeWidths: restored ${this.tableWidths.size} table(s)`);
  }
  persistWidths() {
    if (this.widthSaveTimer !== null) {
      clearTimeout(this.widthSaveTimer);
    }
    this.widthSaveTimer = window.setTimeout(() => {
      this.widthSaveTimer = null;
      this.saveSettings();
      this.log("persistWidths: saved to disk");
    }, 500);
  }
  getTableIdentifier(table) {
    var _a, _b, _c;
    let filePath = "unknown";
    try {
      const views = this.app.workspace.getLeavesOfType("markdown");
      for (const leaf of views) {
        const view = leaf.view;
        if (view && view.contentEl && view.contentEl.contains(table)) {
          filePath = ((_a = view.file) == null ? void 0 : _a.path) || "unknown";
          break;
        }
      }
      if (filePath === "unknown") {
        const activeFile = (_c = (_b = this.app.workspace) == null ? void 0 : _b.getActiveFile) == null ? void 0 : _c.call(_b);
        filePath = activeFile ? activeFile.path : "unknown";
      }
    } catch (error) {
    }
    let tableIndex = 0;
    const container = table.closest(".markdown-source-view, .markdown-preview-view, .markdown-reading-view, .cm-content, .markdown-preview-sizer");
    if (container) {
      const allTables = Array.from(container.querySelectorAll("table"));
      tableIndex = allTables.indexOf(table);
      if (tableIndex < 0)
        tableIndex = 0;
    }
    const dimensions = this.getTableContentHash(table);
    return `${filePath}-idx${tableIndex}-${dimensions}`;
  }
  getTableContentHash(table) {
    const rows = table.querySelectorAll("tr");
    if (rows.length === 0)
      return "empty";
    const firstRow = rows[0];
    const cells = firstRow.querySelectorAll("th, td");
    const columnCount = cells.length;
    let contentHash = "";
    cells.forEach((cell) => {
      var _a;
      const text = ((_a = cell.textContent) == null ? void 0 : _a.trim().substring(0, 30)) || "";
      contentHash += text.replace(/[^a-zA-Z0-9一-龥]/g, "_") + "|";
    });
    return `${columnCount}-${contentHash}`;
  }
  applyStoredWidths(table) {
    const tableId = this.getTableIdentifier(table);
    const storedWidths = this.tableWidths.get(tableId);
    this.log(`applyStoredWidths: table=${tableId}, hasWidths=${!!storedWidths}, count=${(storedWidths == null ? void 0 : storedWidths.size) || 0}`);
    if (storedWidths && storedWidths.size > 0) {
      table.style.tableLayout = "fixed";
      storedWidths.forEach((width, columnIndex) => {
        this.log(`  restoring col=${columnIndex} -> ${width}px`);
        this.applyColumnWidth(table, columnIndex, width);
      });
    }
  }
  updateMarkdownTable(_table) {
  }
  async loadSettings() {
    const data = await this.loadData();
    if (data == null ? void 0 : data.tableWidths) {
      this.deserializeWidths(data.tableWidths);
      delete data.tableWidths;
    }
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData({
      ...this.settings,
      tableWidths: this.serializeWidths()
    });
  }
  onunload() {
    this.log("Plugin unloading...");
    document.removeEventListener("mousemove", this.handleMouseMove);
    document.removeEventListener("mouseup", this.handleMouseUp);
    this.mutationObservers.forEach((observer) => {
      observer.disconnect();
    });
    this.mutationObservers.clear();
    this.log("MutationObservers disconnected");
    this.mutationReapplyPending = false;
    if (this.keyupDebounceTimer !== null) {
      clearTimeout(this.keyupDebounceTimer);
      this.keyupDebounceTimer = null;
    }
    if (this.widthSaveTimer !== null) {
      clearTimeout(this.widthSaveTimer);
      this.widthSaveTimer = null;
    }
    const style = document.getElementById("table-resizer-styles");
    if (style) {
      style.remove();
    }
    const tables = document.querySelectorAll(".table-resizer-active");
    tables.forEach((table) => {
      table.style.tableLayout = "";
      this.disableResizing(table);
    });
    if (this.tableWidths) {
      this.tableWidths.clear();
    }
    this.log("Plugin unloaded");
  }
  dumpTableState(reason) {
    this.log(`=== STATE DUMP: ${reason} ===`);
    const allTables = document.querySelectorAll("table");
    this.log(`  Total tables in DOM: ${allTables.length}`);
    allTables.forEach((t, i) => {
      const htmlTable = t;
      const tableId = this.getTableIdentifier(htmlTable);
      const rows = htmlTable.querySelectorAll("tr");
      const colCount = rows.length > 0 ? rows[0].querySelectorAll("th, td").length : 0;
      const hasClass = htmlTable.classList.contains("table-resizer-active");
      const handleCount = htmlTable.querySelectorAll(".table-resizer-handle").length;
      const stored = this.tableWidths.get(tableId);
      const storedInfo = stored ? Array.from(stored.entries()).map(([c, w]) => `c${c}=${w}px`).join(",") : "none";
      const domWidths = [];
      if (rows.length > 0) {
        rows[0].querySelectorAll("th, td").forEach((cell) => {
          domWidths.push(`${cell.style.width || "auto"}`);
        });
      }
      const tableLayout = htmlTable.style.tableLayout || "auto";
      this.log(`  Table#${i}: id=${tableId}, ${rows.length}x${colCount}, active=${hasClass}, handles=${handleCount}, layout=${tableLayout}, domWidths=[${domWidths.join(",")}], stored=[${storedInfo}]`);
    });
    this.log(`  Stored tableWidths in memory: ${this.tableWidths.size} entries`);
    this.tableWidths.forEach((cols, tid) => {
      this.log(`    ${tid}: [${Array.from(cols.entries()).map(([c, w]) => `c${c}=${w}px`).join(", ")}]`);
    });
    try {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (view && view.editor) {
        const cursor = view.editor.getCursor();
        this.log(`  Cursor: line=${cursor == null ? void 0 : cursor.line}, ch=${cursor == null ? void 0 : cursor.ch}`);
      }
    } catch (e) {
    }
    this.log(`=== STATE DUMP END ===`);
  }
  applyAllStoredWidths() {
    try {
      const tables = document.querySelectorAll(".table-resizer-active");
      this.log(`applyAllStoredWidths: ${tables.length} active table(s)`);
      if (tables.length === 0) {
        this.log("applyAllStoredWidths: no active tables, checking all tables...");
        const allTables = document.querySelectorAll("table");
        this.log(`applyAllStoredWidths: found ${allTables.length} total table(s) in document`);
        allTables.forEach((table) => {
          const htmlTable = table;
          const tableId = this.getTableIdentifier(htmlTable);
          if (this.tableWidths.has(tableId)) {
            this.log(`applyAllStoredWidths: matched non-active table ${tableId}, applying`);
            this.enableResizing(htmlTable);
            this.applyStoredWidths(htmlTable);
          }
        });
        return;
      }
      tables.forEach((table, index) => {
        const htmlTable = table;
        this.log(`applyAllStoredWidths: processing table ${index}`);
        this.applyStoredWidths(htmlTable);
      });
    } catch (error) {
      if (DEBUG_LOGGING)
        console.warn("Error applying stored widths:", error);
    }
  }
};

/* nosourcemap */