/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TabLinkPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/note-index.ts
var TrieNode = class {
  constructor() {
    this.children = /* @__PURE__ */ new Map();
    this.entries = [];
  }
};
var Trie = class {
  constructor() {
    this.root = new TrieNode();
  }
  insert(key, entry) {
    let node = this.root;
    for (const char of key) {
      if (!node.children.has(char)) {
        node.children.set(char, new TrieNode());
      }
      node = node.children.get(char);
    }
    node.entries.push(entry);
  }
  remove(key, path) {
    let node = this.root;
    for (const char of key) {
      if (!node.children.has(char))
        return;
      node = node.children.get(char);
    }
    node.entries = node.entries.filter((e) => e.path !== path);
  }
  // Find all entries with keys starting with prefix
  findByPrefix(prefix) {
    let node = this.root;
    for (const char of prefix) {
      if (!node.children.has(char))
        return [];
      node = node.children.get(char);
    }
    return this.collectAll(node);
  }
  collectAll(node) {
    const results = [...node.entries];
    for (const child of node.children.values()) {
      results.push(...this.collectAll(child));
    }
    return results;
  }
  clear() {
    this.root = new TrieNode();
  }
};
var NoteIndex = class {
  constructor(app) {
    this.entries = /* @__PURE__ */ new Map();
    // lowercase title -> entries
    this.trie = new Trie();
    // O(k) prefix lookups
    this.pathToKeys = /* @__PURE__ */ new Map();
    // path -> keys in entries map (reverse lookup)
    this.excludedFolders = [];
    this.recentLinks = [];
    // Recently linked note paths
    this.MAX_RECENT_LINKS = 50;
    this.app = app;
  }
  setExcludedFolders(folders) {
    this.excludedFolders = folders.map((f) => f.trim().toLowerCase()).filter((f) => f.length > 0);
  }
  isExcluded(path) {
    const lowerPath = path.toLowerCase();
    return this.excludedFolders.some(
      (folder) => lowerPath.startsWith(folder + "/") || lowerPath === folder
    );
  }
  async buildIndex() {
    this.entries.clear();
    this.trie.clear();
    this.pathToKeys.clear();
    const files = this.app.vault.getMarkdownFiles();
    const CHUNK_SIZE = 100;
    for (let i = 0; i < files.length; i += CHUNK_SIZE) {
      const chunk = files.slice(i, i + CHUNK_SIZE);
      for (const file of chunk) {
        if (!this.isExcluded(file.path)) {
          this.indexFile(file);
        }
      }
      if (i + CHUNK_SIZE < files.length) {
        await new Promise((r) => setTimeout(r, 0));
      }
    }
  }
  indexFile(file) {
    var _a, _b, _c;
    const metadataCache = this.app.metadataCache;
    const backlinks = (_a = metadataCache.getBacklinksForFile) == null ? void 0 : _a.call(metadataCache, file);
    const backlinkCount = (_c = (_b = backlinks == null ? void 0 : backlinks.count) == null ? void 0 : _b.call(backlinks)) != null ? _c : 0;
    const title = file.basename;
    this.addEntry(title, {
      title,
      path: file.path,
      isAlias: false,
      backlinkCount
    });
    const cache = this.app.metadataCache.getFileCache(file);
    const aliases = this.getAliases(cache);
    for (const alias of aliases) {
      this.addEntry(alias, {
        title: alias,
        path: file.path,
        isAlias: true,
        backlinkCount
      });
    }
  }
  getAliases(cache) {
    if (!(cache == null ? void 0 : cache.frontmatter))
      return [];
    const aliasValue = cache.frontmatter.aliases || cache.frontmatter.alias;
    if (!aliasValue)
      return [];
    if (Array.isArray(aliasValue)) {
      return aliasValue.filter((a) => typeof a === "string");
    }
    if (typeof aliasValue === "string") {
      return aliasValue.split(",").map((a) => a.trim()).filter((a) => a.length > 0);
    }
    return [];
  }
  addEntry(title, entry) {
    const key = title.toLowerCase();
    const normalizedKey = key.replace(/['']/g, "");
    const existing = this.entries.get(key) || [];
    existing.push(entry);
    this.entries.set(key, existing);
    this.trie.insert(normalizedKey, entry);
    const keysForPath = this.pathToKeys.get(entry.path) || /* @__PURE__ */ new Set();
    keysForPath.add(key);
    this.pathToKeys.set(entry.path, keysForPath);
  }
  removeEntriesForPath(path) {
    const keys = this.pathToKeys.get(path);
    if (!keys)
      return;
    for (const key of keys) {
      const normalizedKey = key.replace(/['']/g, "");
      this.trie.remove(normalizedKey, path);
      const entries = this.entries.get(key);
      if (!entries)
        continue;
      const filtered = entries.filter((e) => e.path !== path);
      if (filtered.length === 0) {
        this.entries.delete(key);
      } else {
        this.entries.set(key, filtered);
      }
    }
    this.pathToKeys.delete(path);
  }
  onFileCreated(file) {
    if (file.extension === "md" && !this.isExcluded(file.path)) {
      this.indexFile(file);
    }
  }
  onFileDeleted(file) {
    if (file.extension === "md") {
      this.removeEntriesForPath(file.path);
    }
  }
  onFileRenamed(file, oldPath) {
    if (file.extension === "md") {
      this.removeEntriesForPath(oldPath);
      if (!this.isExcluded(file.path)) {
        this.indexFile(file);
      }
    }
  }
  onMetadataChanged(file) {
    if (file.extension === "md") {
      this.removeEntriesForPath(file.path);
      if (!this.isExcluded(file.path)) {
        this.indexFile(file);
      }
    }
  }
  /**
   * Fast O(1) check for exact title match.
   * Returns the entry if found, null otherwise.
   */
  hasExactTitle(text, currentFilePath) {
    const key = text.toLowerCase();
    const entries = this.entries.get(key);
    if (!entries)
      return null;
    for (const entry of entries) {
      if (entry.path === currentFilePath)
        continue;
      if (entry.title.toLowerCase() === key) {
        return { entry, key };
      }
    }
    return null;
  }
  recordLinkUsed(path) {
    const index = this.recentLinks.indexOf(path);
    if (index !== -1) {
      this.recentLinks.splice(index, 1);
    }
    this.recentLinks.unshift(path);
    if (this.recentLinks.length > this.MAX_RECENT_LINKS) {
      this.recentLinks.pop();
    }
  }
  /**
   * Find matches for the given query text using O(k) trie lookup.
   * Returns the best match if there's a clear winner, or null if ambiguous/no match.
   */
  findBestMatch(query, currentFilePath, currentFileLinks) {
    if (query.length < 3)
      return null;
    const lowerQuery = query.toLowerCase();
    const normalizedQuery = lowerQuery.replace(/['']/g, "");
    const prefixMatches = this.trie.findByPrefix(normalizedQuery);
    const matches = [];
    for (const entry of prefixMatches) {
      if (entry.path === currentFilePath)
        continue;
      const key = entry.title.toLowerCase().replace(/['']/g, "");
      const score = this.calculateScore(entry, "prefix", normalizedQuery, key, currentFileLinks);
      matches.push({ entry, matchType: "prefix", score });
    }
    if (matches.length === 0)
      return null;
    matches.sort((a, b) => b.score - a.score);
    const best = matches[0];
    if (matches.length === 1)
      return best;
    const second = matches[1];
    if (best.score >= second.score * 2)
      return best;
    const similarMatches = matches.filter((m) => m.score >= best.score * 0.5);
    if (similarMatches.length >= 3)
      return null;
    if (best.score > second.score)
      return best;
    return null;
  }
  calculateScore(entry, matchType, query, entryKey, currentFileLinks) {
    let score = 1e3;
    if (query === entryKey) {
      score += 500;
    }
    score += query.length / entryKey.length * 200;
    if (currentFileLinks.has(entry.path)) {
      score += 5e3;
    }
    const recentIndex = this.recentLinks.indexOf(entry.path);
    if (recentIndex !== -1) {
      score += 2e3 - recentIndex * 20;
    }
    score += Math.min(entry.backlinkCount * 10, 500);
    if (!entry.isAlias) {
      score += 50;
    }
    return score;
  }
  /**
   * Get the completion text (what to show after the typed text)
   */
  getCompletionText(query, matchTitle) {
    const lowerQuery = query.toLowerCase();
    const lowerTitle = matchTitle.toLowerCase();
    const matchIndex = lowerTitle.indexOf(lowerQuery);
    if (matchIndex !== -1) {
      return matchTitle.substring(matchIndex + query.length);
    }
    const normalizedQuery = lowerQuery.replace(/['']/g, "");
    let queryPos = 0;
    let titlePos = 0;
    while (queryPos < normalizedQuery.length && titlePos < matchTitle.length) {
      const titleChar = lowerTitle[titlePos];
      if (titleChar === "'" || titleChar === "'") {
        titlePos++;
        continue;
      }
      if (titleChar === normalizedQuery[queryPos]) {
        queryPos++;
        titlePos++;
      } else {
        return matchTitle;
      }
    }
    if (queryPos === normalizedQuery.length) {
      return matchTitle.substring(titlePos);
    }
    return matchTitle;
  }
};

// src/ghost-text.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var COMMON_WORDS = /* @__PURE__ */ new Set([
  "the",
  "and",
  "for",
  "with",
  "that",
  "this",
  "from",
  "have",
  "been",
  "were",
  "what",
  "when",
  "where",
  "which",
  "their",
  "there",
  "about",
  "would",
  "could",
  "should",
  "these",
  "those",
  "then",
  "than",
  "into",
  "some",
  "other",
  "more",
  "very",
  "just",
  "also",
  "like",
  "only",
  "will",
  "can",
  "are",
  "has",
  "was",
  "but",
  "not",
  "you",
  "all",
  "any",
  "her",
  "his",
  "its",
  "our",
  "out",
  "own",
  "she",
  "who",
  "how",
  "may",
  "new",
  "now",
  "old",
  "see",
  "way",
  "day",
  "get",
  "come",
  "made",
  "find",
  "here",
  "many",
  "most",
  "must",
  "said",
  "each",
  "make",
  "over",
  "such",
  "take",
  "them",
  "well",
  "only"
]);
var setSuggestion = import_state.StateEffect.define();
var clearSuggestion = import_state.StateEffect.define();
var suggestionField = import_state.StateField.define({
  create() {
    return null;
  },
  update(value, tr) {
    for (const effect of tr.effects) {
      if (effect.is(setSuggestion)) {
        return effect.value;
      }
      if (effect.is(clearSuggestion)) {
        return null;
      }
    }
    if (value && tr.docChanged) {
      let affected = false;
      tr.changes.iterChangedRanges((fromA, toA) => {
        if (fromA <= value.queryEnd) {
          affected = true;
        }
      });
      if (affected) {
        return null;
      }
    }
    if (value && tr.selection) {
      const newPos = tr.selection.main.head;
      if (newPos !== value.queryEnd) {
        return null;
      }
    }
    return value;
  }
});
var GhostTextWidget = class extends import_view.WidgetType {
  constructor(text) {
    super();
    this.text = text;
  }
  toDOM() {
    const span = document.createElement("span");
    span.className = "tab-link-ghost-text";
    span.textContent = this.text;
    return span;
  }
  eq(other) {
    return this.text === other.text;
  }
};
function createGhostDecoration(suggestion) {
  const widget = import_view.Decoration.widget({
    widget: new GhostTextWidget(suggestion.completionText),
    side: 1
    // After cursor
  });
  return import_view.Decoration.set([widget.range(suggestion.queryEnd)]);
}
var ghostDecorationField = import_state.StateField.define({
  create() {
    return import_view.Decoration.none;
  },
  update(decorations, tr) {
    const suggestion = tr.state.field(suggestionField);
    if (suggestion) {
      return createGhostDecoration(suggestion);
    }
    return import_view.Decoration.none;
  },
  provide: (field) => import_view.EditorView.decorations.from(field)
});
function isInsideLink(state, pos) {
  const line = state.doc.lineAt(pos);
  const lineText = line.text;
  const posInLine = pos - line.from;
  const beforeCursor = lineText.substring(0, posInLine);
  const lastOpenBracket = beforeCursor.lastIndexOf("[[");
  const lastCloseBracket = beforeCursor.lastIndexOf("]]");
  if (lastOpenBracket !== -1 && lastOpenBracket > lastCloseBracket) {
    return true;
  }
  if (beforeCursor.endsWith("[[")) {
    return true;
  }
  return false;
}
function isInFrontmatter(state, pos) {
  const doc = state.doc;
  if (doc.lines < 1)
    return false;
  if (doc.line(1).text !== "---")
    return false;
  const currentLine = doc.lineAt(pos).number;
  for (let i = 2; i <= doc.lines; i++) {
    const lineText = doc.line(i).text;
    if (lineText === "---") {
      return currentLine < i;
    }
  }
  return true;
}
function isInCodeBlock(state, pos) {
  const line = state.doc.lineAt(pos);
  const textBefore = line.text.substring(0, pos - line.from);
  const backticks = (textBefore.match(/`/g) || []).length;
  if (backticks % 2 === 1)
    return true;
  let inFence = false;
  for (let i = 1; i < line.number; i++) {
    const lineText = state.doc.line(i).text;
    if (lineText.startsWith("```")) {
      inFence = !inFence;
    }
  }
  return inFence;
}
function extractTrailingText(state, pos) {
  const line = state.doc.lineAt(pos);
  const lineText = line.text;
  const posInLine = pos - line.from;
  const textBefore = lineText.substring(0, posInLine);
  let start = posInLine;
  let foundWordChar = false;
  for (let i = posInLine - 1; i >= 0; i--) {
    const char = textBefore[i];
    if (i >= 1 && textBefore.substring(i - 1, i + 1) === "[[") {
      break;
    }
    if (char === "[" || char === "]") {
      break;
    }
    if (char === "." || char === "!" || char === "?" || char === ":" || char === ";") {
      break;
    }
    if (char === " ") {
      if (!foundWordChar) {
        const nextChar = i > 0 ? textBefore[i - 1] : null;
        if (nextChar === " " || nextChar === null) {
          break;
        }
        continue;
      }
      const currentPhrase = textBefore.substring(i + 1, posInLine);
      const wordCount = currentPhrase.trim().split(/\s+/).length;
      if (wordCount >= 6) {
        break;
      }
      start = i + 1;
      continue;
    }
    if (/[a-zA-Z0-9\-_']/.test(char)) {
      foundWordChar = true;
      start = i;
    } else {
      break;
    }
  }
  if (start >= posInLine) {
    return null;
  }
  const fullText = textBefore.substring(start, posInLine).trim();
  if (!fullText)
    return null;
  const words = [];
  const starts = [];
  let wordStart = -1;
  for (let i = start; i < posInLine; i++) {
    const char = textBefore[i];
    const isWordChar = /[a-zA-Z0-9\-_']/.test(char);
    if (isWordChar && wordStart === -1) {
      wordStart = i;
    } else if (!isWordChar && wordStart !== -1) {
      words.push(textBefore.substring(wordStart, i));
      starts.push(line.from + wordStart);
      wordStart = -1;
    }
  }
  if (wordStart !== -1) {
    words.push(textBefore.substring(wordStart, posInLine));
    starts.push(line.from + wordStart);
  }
  if (words.length === 0)
    return null;
  return {
    words,
    starts,
    fullText,
    fullStart: line.from + start
  };
}
function isCommonWord(text) {
  return COMMON_WORDS.has(text.toLowerCase());
}
function isCursorAtWordEnd(state, pos) {
  const line = state.doc.lineAt(pos);
  const posInLine = pos - line.from;
  if (posInLine >= line.text.length) {
    return true;
  }
  const nextChar = line.text[posInLine];
  return !/[a-zA-Z0-9]/.test(nextChar);
}
function createGhostTextPlugin(config) {
  return import_view.ViewPlugin.define((view) => {
    let debounceTimer = null;
    function scheduleUpdate(view2) {
      if (debounceTimer) {
        clearTimeout(debounceTimer);
      }
      debounceTimer = setTimeout(() => {
        updateSuggestion(view2);
      }, config.debounceMs);
    }
    function updateSuggestion(view2) {
      const state = view2.state;
      const selection = state.selection.main;
      if (!selection.empty) {
        view2.dispatch({ effects: clearSuggestion.of() });
        return;
      }
      const pos = selection.head;
      if (isInsideLink(state, pos)) {
        view2.dispatch({ effects: clearSuggestion.of() });
        return;
      }
      if (isInFrontmatter(state, pos)) {
        view2.dispatch({ effects: clearSuggestion.of() });
        return;
      }
      if (isInCodeBlock(state, pos)) {
        view2.dispatch({ effects: clearSuggestion.of() });
        return;
      }
      if (!isCursorAtWordEnd(state, pos)) {
        view2.dispatch({ effects: clearSuggestion.of() });
        return;
      }
      const trailing = extractTrailingText(state, pos);
      if (!trailing || trailing.words.length === 0) {
        view2.dispatch({ effects: clearSuggestion.of() });
        return;
      }
      const currentFilePath = config.getCurrentFilePath();
      const currentFileLinks = config.getCurrentFileLinks();
      for (let len = trailing.words.length; len >= 1; len--) {
        const phraseWords = trailing.words.slice(-len);
        const phrase = phraseWords.join(" ");
        if (phrase.length < config.minChars)
          continue;
        const exactMatch = config.noteIndex.hasExactTitle(phrase, currentFilePath);
        if (exactMatch) {
          const start = trailing.starts[trailing.words.length - len];
          const completionText2 = config.noteIndex.getCompletionText(
            phrase,
            exactMatch.entry.title
          );
          if (!completionText2) {
            view2.dispatch({ effects: clearSuggestion.of() });
            return;
          }
          const suggestion2 = {
            query: phrase,
            queryStart: start,
            queryEnd: pos,
            fullTitle: exactMatch.entry.title,
            completionText: completionText2,
            notePath: exactMatch.entry.path
          };
          view2.dispatch({ effects: setSuggestion.of(suggestion2) });
          return;
        }
      }
      const currentWord = trailing.words[trailing.words.length - 1];
      const currentWordStart = trailing.starts[trailing.starts.length - 1];
      const fullPhrase = trailing.fullText;
      const normalizeForMatch = (s) => s.toLowerCase().replace(/['']/g, "");
      let match = null;
      let queryText = currentWord;
      let queryStart = currentWordStart;
      if (fullPhrase.length >= config.minChars && trailing.words.length > 1) {
        const phraseMatch = config.noteIndex.findBestMatch(
          fullPhrase,
          currentFilePath,
          currentFileLinks
        );
        if (phraseMatch) {
          const normalizedTitle = normalizeForMatch(phraseMatch.entry.title);
          const normalizedPhrase = normalizeForMatch(fullPhrase);
          if (normalizedTitle.startsWith(normalizedPhrase)) {
            match = phraseMatch;
            queryText = fullPhrase;
            queryStart = trailing.fullStart;
          }
        }
      }
      if (!match) {
        if (currentWord.length < config.minChars) {
          view2.dispatch({ effects: clearSuggestion.of() });
          return;
        }
        if (isCommonWord(currentWord)) {
          view2.dispatch({ effects: clearSuggestion.of() });
          return;
        }
        match = config.noteIndex.findBestMatch(
          currentWord,
          currentFilePath,
          currentFileLinks
        );
        if (!match) {
          view2.dispatch({ effects: clearSuggestion.of() });
          return;
        }
        if (trailing.words.length > 1) {
          const normalizedTitle = normalizeForMatch(match.entry.title);
          const normalizedPhrase = normalizeForMatch(fullPhrase);
          if (normalizedTitle.startsWith(normalizedPhrase)) {
            queryText = fullPhrase;
            queryStart = trailing.fullStart;
          }
        }
      }
      const completionText = config.noteIndex.getCompletionText(
        queryText,
        match.entry.title
      );
      if (!completionText) {
        view2.dispatch({ effects: clearSuggestion.of() });
        return;
      }
      const suggestion = {
        query: queryText,
        queryStart,
        queryEnd: pos,
        fullTitle: match.entry.title,
        completionText,
        notePath: match.entry.path
      };
      view2.dispatch({ effects: setSuggestion.of(suggestion) });
    }
    return {
      update(update) {
        if (update.selectionSet && !update.docChanged) {
          if (debounceTimer) {
            clearTimeout(debounceTimer);
            debounceTimer = null;
          }
          setTimeout(() => {
            update.view.dispatch({ effects: clearSuggestion.of() });
          }, 0);
          return;
        }
        if (update.docChanged) {
          scheduleUpdate(update.view);
        }
      },
      destroy() {
        if (debounceTimer) {
          clearTimeout(debounceTimer);
        }
      }
    };
  });
}
function acceptSuggestion(view, config) {
  const suggestion = view.state.field(suggestionField, false);
  if (!suggestion) {
    return false;
  }
  const linkText = config.autoSpace ? `[[${suggestion.fullTitle}]] ` : `[[${suggestion.fullTitle}]]`;
  view.dispatch({
    changes: {
      from: suggestion.queryStart,
      to: suggestion.queryEnd,
      insert: linkText
    },
    effects: clearSuggestion.of(),
    selection: { anchor: suggestion.queryStart + linkText.length }
  });
  config.onLinkInserted(suggestion.notePath);
  return true;
}
function dismissSuggestion(view) {
  const suggestion = view.state.field(suggestionField, false);
  if (!suggestion) {
    return false;
  }
  view.dispatch({ effects: clearSuggestion.of() });
  return true;
}
function createGhostTextKeymap(config) {
  return import_state.Prec.highest(import_view.keymap.of([
    {
      key: "Tab",
      run: (view) => acceptSuggestion(view, config)
    },
    {
      key: "Escape",
      run: dismissSuggestion
    },
    {
      key: "ArrowLeft",
      run: dismissSuggestion
    },
    {
      key: "ArrowRight",
      run: dismissSuggestion
    },
    {
      key: "ArrowUp",
      run: dismissSuggestion
    },
    {
      key: "ArrowDown",
      run: dismissSuggestion
    },
    {
      key: "Space",
      run: (view) => {
        dismissSuggestion(view);
        return false;
      }
    }
  ]));
}
function getGhostTextExtensions(config) {
  return [
    suggestionField,
    ghostDecorationField,
    createGhostTextPlugin(config),
    createGhostTextKeymap(config)
  ];
}

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  enabled: true,
  autoSpace: true,
  excludedFolders: "",
  minChars: 5,
  debounceMs: 150
};
var TabLinkSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Enable ghost text suggestions").setDesc("Show ghost text completions for note links while typing").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
        this.plugin.settings.enabled = value;
        await this.plugin.saveSettings();
        this.plugin.refreshEditorExtensions();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-space after link").setDesc("Automatically add a space after accepting a link with tab").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSpace).onChange(async (value) => {
        this.plugin.settings.autoSpace = value;
        await this.plugin.saveSettings();
        this.plugin.refreshEditorExtensions();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Excluded folders").setDesc("Comma-separated list of folder paths to ignore (e.g., templates, daily-notes)").addText(
      (text) => text.setPlaceholder("Templates, archive/daily-notes").setValue(this.plugin.settings.excludedFolders).onChange(async (value) => {
        this.plugin.settings.excludedFolders = value;
        await this.plugin.saveSettings();
        this.plugin.updateExcludedFolders();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Minimum characters").setDesc("Minimum number of characters before showing suggestions (3-8)").addSlider(
      (slider) => slider.setLimits(3, 8, 1).setValue(this.plugin.settings.minChars).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.minChars = value;
        await this.plugin.saveSettings();
        this.plugin.refreshEditorExtensions();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Debounce delay (ms)").setDesc("How long to wait after typing before showing suggestions (100-500ms)").addSlider(
      (slider) => slider.setLimits(100, 500, 25).setValue(this.plugin.settings.debounceMs).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.debounceMs = value;
        await this.plugin.saveSettings();
        this.plugin.refreshEditorExtensions();
      })
    );
  }
};

// main.ts
var TabLinkPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.editorExtensions = [];
  }
  async onload() {
    await this.loadSettings();
    this.noteIndex = new NoteIndex(this.app);
    this.updateExcludedFolders();
    this.app.workspace.onLayoutReady(async () => {
      await this.noteIndex.buildIndex();
    });
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian2.TFile) {
          this.noteIndex.onFileCreated(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian2.TFile) {
          this.noteIndex.onFileDeleted(file);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian2.TFile) {
          this.noteIndex.onFileRenamed(file, oldPath);
        }
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        this.noteIndex.onMetadataChanged(file);
      })
    );
    this.setupEditorExtensions();
    this.addSettingTab(new TabLinkSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  updateExcludedFolders() {
    const folders = this.settings.excludedFolders.split(",").map((f) => f.trim()).filter((f) => f.length > 0);
    this.noteIndex.setExcludedFolders(folders);
    void this.noteIndex.buildIndex();
  }
  getGhostTextConfig() {
    return {
      noteIndex: this.noteIndex,
      minChars: this.settings.minChars,
      debounceMs: this.settings.debounceMs,
      autoSpace: this.settings.autoSpace,
      getCurrentFilePath: () => {
        var _a, _b;
        const view = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
        return (_b = (_a = view == null ? void 0 : view.file) == null ? void 0 : _a.path) != null ? _b : null;
      },
      getCurrentFileLinks: () => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
        if (!(view == null ? void 0 : view.file))
          return /* @__PURE__ */ new Set();
        const cache = this.app.metadataCache.getFileCache(view.file);
        const links = /* @__PURE__ */ new Set();
        if (cache == null ? void 0 : cache.links) {
          for (const link of cache.links) {
            const linkedFile = this.app.metadataCache.getFirstLinkpathDest(
              link.link,
              view.file.path
            );
            if (linkedFile) {
              links.add(linkedFile.path);
            }
          }
        }
        return links;
      },
      onLinkInserted: (path) => {
        this.noteIndex.recordLinkUsed(path);
      }
    };
  }
  setupEditorExtensions() {
    if (this.settings.enabled) {
      const config = this.getGhostTextConfig();
      const extensions = getGhostTextExtensions(config);
      this.editorExtensions.push(...extensions);
    }
    this.registerEditorExtension(this.editorExtensions);
  }
  refreshEditorExtensions() {
    this.editorExtensions.length = 0;
    if (this.settings.enabled) {
      const config = this.getGhostTextConfig();
      const extensions = getGhostTextExtensions(config);
      this.editorExtensions.push(...extensions);
    }
    this.app.workspace.updateOptions();
  }
};

/* nosourcemap */